services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    environment:
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - RUST_LOG=debug
    
volumes:
  cargo-cache:
  target-cache: 