[package]
name = "management"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1.83"

[lib]
name = "management"
path = "src/lib.rs"